structures/urls.py
"""Tasks for Structures."""

from django.urls import path

from . import views

app_name = "structures"

urlpatterns = [
    path("", views.index, name="index"),
    path("list", views.main, name="main"),
    path("list_data", views.structure_list_data, name="structure_list_data"),
    path("summary_data", views.structure_summary_data, name="structure_summary_data"),
    path("add_structure_owner", views.add_structure_owner, name="add_structure_owner"),
    path("poco_list_data", views.poco_list_data, name="poco_list_data"),
    path(
        "jump_gates_list_data", views.jump_gates_list_data, name="jump_gates_list_data"
    ),
    path("service_status", views.service_status, name="service_status"),
    path(
        "<int:structure_id>/structure_details",
        views.structure_details,
        name="structure_details",
    ),
    path(
        "<int:structure_id>/poco_details",
        views.poco_details,
        name="poco_details",
    ),
    path(
        "<int:structure_id>/starbase_detail",
        views.starbase_detail,
        name="starbase_detail",
    ),
]

structures/templates/structures/partials/jump_gates_list.html
{% load i18n %}
{% load bootstrap %}
{% load static %}

<!-- structure list -->
<div role="tabpanel" class="tab-pane" id="jump-gates">
    <div class="table-responsive">
        <table id="tab_jump_gates" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Owner" %}</th>
                    <th>{% translate "Location" %}</th>
                    <th>{% translate "Name" %}</th>
                    <th>{% translate "Last Online" %}</th>
                    <th>{% translate "Fuel Expires" %}</th>
                    <th>{% translate "Liquid Ozone (units)" %}</th>
                </tr>
            </thead>
        </table>
        <p class="text-muted">
            {% translate "Reinforced structures (except POCOs) are highlighted in red" %}
        </p>
    </div>
</div>

<!-- Modals -->
<div class="modal" id="modalUpwellDetails" tabindex="-1" role="dialog" aria-labelledby="{% translate 'modalUpwellDetails '%}">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalUpwellDetailsContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

structures/templates/structures/partials/poco_list.html
{% load i18n %}
{% load bootstrap %}

<div role="tabpanel" class="tab-pane" id="pocos">
    <div class="table-responsive">
        <table id="tab_pocos" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Region" %}</th>
                    <th>{% translate "Solar System" %}</th>
                    <th>{% translate "Planet" %}</th>
                    <th></th>
                    <th>{% translate "Planet Type" %}</th>
                    <th class="text-tooltip" title="For your main character {{ request.user.profile.main_character|default:'?' }}">
                        {% translate "Access?" %}
                    </th>
                    <th class="text-tooltip" title="For your main character {{ request.user.profile.main_character|default:'?' }}">
                        {% translate "Tax" %}
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>

structures/templates/structures/partials/structure_list.html
{% load i18n %}
{% load bootstrap %}
{% load static %}

<!-- structure list -->
<div role="tabpanel" class="tab-pane" id="structures">
    <div class="table-responsive">
        <!-- Tags Filter Button -->
        <span class="pull-right">
            {% if tags_exist %}
                {% if active_tags %}
                    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalTagsFilter">
                    {% translate "Tags Filter (Active)" %}
                    </button>
                {% else %}
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalTagsFilter">
                        {% translate "Tags Filter" %}
                    </button>
                {% endif %}
            {% else %}
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalTagsFilter" disabled="disabled">
                    {% translate "Tags Filter" %}
                </button>
            {% endif %}
        </span>

        <!-- Tags Filter Modal -->
        <div class="modal" id="modalTagsFilter" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <form method="post">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">{% translate "Tags Filter" %}</h4>
                        </div>
                        <div class="modal-body">
                            {% csrf_token %}
                            {{ tags_filter_form|bootstrap }}
                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-default pull-left" href="{% url 'structures:index' %}" role="button">
                                {% translate "Reset Filter" %}
                            </a>
                            <a class="btn btn-default pull-left" href="{% url 'structures:main' %}" role="button">
                                {% translate "Clear Filter" %}
                            </a>
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                {% translate "Cancel" %}
                            </button>
                            <button type="submit" class="btn btn-primary">
                                {% translate "Apply Filter" %}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <table id="tab_structures" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Owner" %}</th>
                    <th>{% translate "Location" %}</th>
                    <th></th>
                    <th>{% translate "Type" %}</th>
                    <th>{% translate "Name & Tags" %}</th>
                    <th>{% translate "Services" %}</th>
                    <th>{% translate "Last Online" %}</th>
                    <th>{% translate "Fuel Expires" %}</th>
                    <th>{% translate "R-Hour" %}</th>
                    <th>{% translate "State" %}</th>
                    <th>{% translate "Core" %}</th>
                    <th></th>
                </tr>
            </thead>
        </table>

        <p>
            {% if active_tags %}
                {% translate "Active Tags Filter" %}:&nbsp;
                {% for tag in active_tags %}
                    {{ tag.html }}&#32;
                {% endfor %}
            {% endif %}
        </p>
        <p class="text-muted">
            {% translate "Offlined services are shown as" %} <del>{% translate "service" %}</del>
            • {% translate "Reinforced structures (except POCOs) are highlighted in red" %}
        </p>
    </div>
</div>

<!-- Modals -->
<div class="modal" id="modalUpwellDetails" tabindex="-1" role="dialog" aria-labelledby="{% translate 'modalUpwellDetails '%}">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalUpwellDetailsContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modalPocoDetails" tabindex="-1" role="dialog" aria-labelledby="modalPocoDetails">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalPocoDetailsContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modalStarbaseDetail" tabindex="-1" role="dialog" aria-labelledby="modalStarbaseDetail">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalStarbaseDetailContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

structures/templates/structures/partials/structure_summary.html
{% load i18n %}
{% load bootstrap %}

<div role="tabpanel" class="tab-pane" id="summary">
    <div class="table-responsive">
        <table id="tab_summary" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Corporation" %}</th>
                    <th>{% translate "Alliance" %}</th>
                    <th class="text-right">{% translate "Citadels" %}</th>
                    <th class="text-right">{% translate "Engineering Complexes" %}</th>
                    <th class="text-right">{% translate "Refineries" %}</th>
                    <th class="text-right">{% translate "Other Upwell" %}</th>
                    <th class="text-right">{% translate "Customs Offices" %}</th>
                    <th class="text-right">{% translate "Starbases" %}</th>
                    <th class="text-right">{% translate "Total" %}</th>
                </tr>
            </thead>
            <tfoot>
                <tr class="info">
                    <th></th>
                    <th>{% translate "Total" %}</th>
                    <th></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>